export const categories = [
  {
    categoryId: '1',
    name: 'Burgers',
    description: 'Juicy burgers made with 100% beef',
    image: {
      url: 'burgers.jpg',
      alt: 'Juicy burgers made with 100% beef',
    },
  },
  {
    categoryId: '2',
    name: 'Chicken',
    description: 'Crispy chicken sandwiches and tenders',
    image: {
      url: 'chicken.jpg',
      alt: 'Crispy chicken sandwiches and tenders',
    },
  },
  {
    categoryId: '3',
    name: 'Sides',
    description: 'Delicious sides to complement your meal',
    image: {
      url: 'sides.jpg',
      alt: 'Delicious sides to complement your meal',
    },
  },
  {
    categoryId: '4',
    name: 'Beverages',
    description: 'Whatever you need to quench your thirst',
    image: {
      url: 'drinks.jpg',
      alt: 'Whatever you need to quench your thirst',
    },
  },
  {
    categoryId: '5',
    name: 'Desserts',
    description: 'Sweet treats to satisfy your cravings',
    image: {
      url: 'desserts.jpg',
      alt: 'Sweet treats to satisfy your cravings',
    },
  },
];

export const items = [
  {
    productId: '101',
    name: 'Pepperoni Pizza',
    price: 999,
    image: {
      url: 'pepperoni-pizza.jpeg',
      alt: 'Regular pizza with pepperoni and mozzarella',
    },
  },
  {
    productId: '102',
    name: 'Cheeseburger',
    price: 699,
    image: {
      url: 'cheeseburger.jpeg',
      alt: 'A juicy cheeseburger generated by Dall-E. So. Many. Pickles.',
    },
  },
  {
    productId: '103',
    name: 'Crunchy Tacos',
    price: 850,
    image: {
      url: 'tacos-two.jpeg',
      alt: 'Spicy chicken tacos with salsa and guacamole',
    },
  },
];
