export const items = [
  {
    productId: '101',
    name: 'Pepperoni Pizza',
    price: 999,
    image: {
      url: 'pepperoni-pizza.jpeg',
      alt: 'Regular pizza with pepperoni and mozzarella',
    },
  },
  {
    productId: '102',
    name: 'Cheeseburger',
    price: 699,
    image: {
      url: 'cheeseburger.jpeg',
      alt: 'A juicy cheeseburger generated by Dall-E. So. Many. Pickles.',
    },
  },
  {
    productId: '103',
    name: 'Crunchy Tacos',
    price: 850,
    image: {
      url: 'tacos-two.jpeg',
      alt: 'Spicy chicken tacos with salsa and guacamole',
    },
  },
];
